# name: CD Pipeline

# on:
#     workflow_run:
#         workflows: ["CI Pipeline"]
#         types:
#             - completed
# jobs:

#   build:

#     runs-on: self-hosted

#     steps:
    
#     - name: Login Dockerhub 
#       env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

#     - name: Pull Docker Image
#       run: sudo docker pull yuriydobboz/ci-cd-aws-docker:latest
    
#     - name: Delete Old docker container
#       run: sudo docker rm -f ci-cd-aws-docker-container || true  

#     - name: Run Docker Container
#       run: sudo docker run -d -p 80:5000 --name ci-cd-aws-docker-container yuriydobboz/ci-cd-aws-docker

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        envs: DOCKER_USERNAME, DOCKER_PASSWORD
        script: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker pull yuriydobboz/ci-cd-aws-docker:latest
          docker rm -f ci-cd-aws-docker-container || true
          docker run -d -p 80:5000 --name ci-cd-aws-docker-container yuriydobboz/ci-cd-aws-docker:latest
