name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed
jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Pull Docker Image
      run: sudo docker pull yuriydobboz/ci-cd-aws-docker:latest
    
    - name: Delete Old docker container
      run: sudo docker rm -f ci-cd-aws-docker-container || true  

    - name: Run Docker Container
      run: sudo docker run -d -p 5000:80 --name ci-cd-aws-docker-container yuriydobboz/ci-cd-aws-docker